#-------------------------------
# Site Settings
title: Bianca Azartash
logo: # You can add own logo. For example '/images/logo.png'.
description: A Digital Grimoire


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'Portfolio'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'
 #   - title: 'AI & Instruction Guides'
 #     url: '/styleguide/'


#-------------------------------
# Author Settings
author:
  name: Bianca Azartash
  avatar: '/images/3436.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Memento Modeli
  description: "Marginalia of a Librarian: Enchantment, Contextualized"
  subtitle: "AI Literacy and Librarianship in the Digital Age"
  image: '/images/banner.png'


#-------------------------------
# Contact Settings
contact:
  email: bianca.azartash@ou.edu # Add your email for contact form
  # description: Norlin comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
#- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
#- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
#- {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
#- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
#- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
#- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/undomielren-lib"}
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/bianca-azartash/"}
#- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
newsletter: enable
newsletter-title: Get Updates
newsletter-subtitle: "Substack: AI literacy and librarianship in the digital age."
newsletter-url: "https://mementomodeli.substack.com"
newsletter-button-text: Subscribe
